name: Jest Tests
on:
  push:
    branches: [staging, dev]
  # pull_request:
  #   branches: [ staging, dev ]
  deployment_status:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.6

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run jest
        env:
          NODE_ENV: development
